LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_CERTIFICATE   := platform
LOCAL_MODULE        := OpenCamera
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := zte
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS   := optional
LOCAL_SRC_FILES     := priv-app/OpenCamera.apk
include $(BUILD_PREBUILT)
